# Generated by Django 6.0.6 on 2026-07-20 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("points", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoreevents",
                        to="competitions.competition",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoreevents",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["competition"], name="scoreevents_competi_78d4c5_idx"
                    ),
                    models.Index(
                        fields=["participant"], name="scoreevents_partici_31b582_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="scoreevents_created_200895_idx"
                    ),
                ],
            },
        ),
    ]
