# Generated by Django 6.0.6 on 2026-06-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scoring_rules', models.JSONField(blank=True, default=dict)),
                ('reset_type', models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='accounts.app')),
            ],
        ),
    ]
